n = int(input('Digite o numero: '))
print('{} x 0 = {}' .format(n, n*0))
print('{} x 1 = {}' .format(n, n*1))
print('{} x 2 = {}' .format(n, n*2))
print('{} x 3 = {}' .format(n, n*3))
print('{} x 4 = {}' .format(n, n*4))
print('{} x 5 = {}' .format(n, n*5))
print('{} x 6 = {}' .format(n, n*6))